
export default {
  LOAD_STARTED_ACTIVITIES: "LOAD_STARTED_ACTIVITIES",
  LOAD_SUCCEEDED_ACTIVITIES: "LOAD_SUCCEEDED_ACTIVITIES",
  LOAD_FAILED_ACTIVITIES: "LOAD_FAILED_ACTIVITIES",

  LOAD_STARTED: "LOAD_STARTED",
  LOAD_SUCCEEDED: "LOAD_SUCCEEDED",
  LOAD_FAILED: "LOAD_FAILED",
}