
export default {
  LOAD_STARTED_ACTIVITIES: "LOAD_STARTED_ACTIVITIES",
  LOAD_SUCCEEDED_ACTIVITIES: "LOAD_SUCCEEDED_ACTIVITIES",
  LOAD_FAILED_ACTIVITIES: "LOAD_FAILED_ACTIVITIES",

  LOAD_STARTED_CITIES: "LOAD_STARTED_CITIES",
  LOAD_SUCCEEDED_CITIES: "LOAD_SUCCEEDED_CITIES",
  LOAD_FAILED_CITIES: "LOAD_FAILED_CITIES",

  LOAD_STARTED_COUNTRIES: "LOAD_STARTED_COUNTRIES",
  LOAD_SUCCEEDED_COUNTRIES: "LOAD_SUCCEEDED_COUNTRIES",
  LOAD_FAILED_COUNTRIES: "LOAD_FAILED_COUNTRIES",

  LOAD_STARTED_ROUTES: "LOAD_STARTED_ROUTES",
  LOAD_SUCCEEDED_ROUTES: "LOAD_SUCCEEDED_ROUTES",
  LOAD_FAILED_ROUTES: "LOAD_FAILED_ROUTES",

  LOAD_STARTED_TYPOLOGIES: "LOAD_STARTED_TYPOLOGIES",
  LOAD_SUCCEEDED_TYPOLOGIES: "LOAD_SUCCEEDED_TYPOLOGIES",
  LOAD_FAILED_TYPOLOGIES: "LOAD_FAILED_TYPOLOGIES",

  LOAD_STARTED: "LOAD_STARTED",
  LOAD_SUCCEEDED: "LOAD_SUCCEEDED",
  LOAD_FAILED: "LOAD_FAILED",
}